name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-18"

# compatibility_flags = [ "nodejs_compat" ]

[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTFiZmU1NGEtNGRmMy00MDI3LTljMWMtY2E0OGI3YjhiZGQwIiwidGVuYW50X2lkIjoiYTBmMzYxOGUwY2U4NGQ3NGVjMzU0ZDIwOWQ2NTVlY2Q0NDcyZGVkZjE2NmZkNDk5YmM0ZjdlMGE2ZGVlMjgwYyIsImludGVybmFsX3NlY3JldCI6ImZmZGFkMmJjLTFlMTEtNDA3NS05ZjFkLTZiZDJmM2Q3MDc3ZCJ9.Bf0nvIXEwr9Ixm2ziLE_348g9tqvuZudzuuvX4Pw07w"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1